### ISSUE TITLE
Error I receive when using the turtle rod.

### ISSUE THREAD

**Issue by EqlipseD** [Nubebuster/Mining-Turtles#2]
[15:58:35] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to MiningTurtles v1.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-2f787bd-ea28011]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-2f787bd-ea28011]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-2f787bd-ea28011]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-2f787bd-ea28011]
    at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:227) [spigot.jar:git-Spigot-2f787bd-ea28011]
    at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:194) [spigot.jar:git-Spigot-2f787bd-ea28011]
    at net.minecraft.server.v1_8_R2.PlayerInteractManager.a(PlayerInteractManager.java:107) [spigot.jar:git-Spigot-2f787bd-ea28011]
    at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:598) [spigot.jar:git-Spigot-2f787bd-ea28011]
    at net.minecraft.server.v1_8_R2.PacketPlayInBlockDig.a(SourceFile:40) [spigot.jar:git-Spigot-2f787bd-ea28011]
    at net.minecraft.server.v1_8_R2.PacketPlayInBlockDig.a(SourceFile:10) [spigot.jar:git-Spigot-2f787bd-ea28011]
    at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-2f787bd-ea28011]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
    at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-2f787bd-ea28011]
    at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-2f787bd-ea28011]
    at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-2f787bd-ea28011]
    at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-2f787bd-ea28011]
    at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-2f787bd-ea28011]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/EntityHuman
    at me.Mark.MT.Listeners.PlayerListener.onInteract(PlayerListener.java:38) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor142.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-2f787bd-ea28011]
    ... 18 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.EntityHuman
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-2f787bd-ea28011]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-2f787bd-ea28011]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
    at me.Mark.MT.Listeners.PlayerListener.onInteract(PlayerListener.java:38) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor142.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-2f787bd-ea28011]
    ... 18 more

**Comment by NubeBuster** [comment]
This seems like it could be caused by using a different version of spigot.
Are you running the latest build. If so, the problem lies in the plugin, then I'll need to update the reference library.
Could you give the version string of your spigot? you run the command "ver" in your console and then copy the output.

Thanks for reporting this bug.

[Edit] The plugin is built on "CraftBukkit version git-Spigotd2856ae-8f0f4ed (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT)"
Which is 22 versions behind. But I don't think this is the problem.

**Comment by EqlipseD** [comment]
I am not running the latest Spigot, some of the plugins that I use clash with it and do not work. Here is the version I am currently using: git-Spigot-2f787bd-ea28011 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)

**Comment by NubeBuster** [comment]
You are using an outdated version. I can downgrade the plugin for you if you want. Tell me if so.

**Comment by EqlipseD** [comment]
That would be amazing if you could that. Thank you ahead of time, my good sir!

**Comment by EqlipseD** [comment]
When do you think you might be able to do that for me?

**Comment by NubeBuster** [comment]
Oh im sorry for the late reply. Somehow i got no notification email for this. Could you send me your server jar? Then i can build upon that.

**Comment by EqlipseD** [comment]
Okay, here it is: https://www.mediafire.com/?ooc0re7mafo80hm, I didn't know where else to upload it, sorry.

**Comment by NubeBuster** [comment]
Here it is: http://www.mediafire.com/download/rz4t2d6qtts48tw/Mining_Turtles_1.8.3.jar

**Comment by EqlipseD** [comment]
Thank you. It loads up and seems to be working. I just can't seem to understand how to use this. I posted my issue on the discussion section of Spigot. Thank you in advance.
